"use client";
import {useEffect,useRef,useState,type ReactNode} from "react";
import {createPortal} from "react-dom";
import {Camera,Check,Copy,EyeOff,Link2,MapPin,MoreHorizontal,RefreshCw,ShieldOff,Trash2,UserPlus,Users,X} from "lucide-react";
import {QRCodeSVG} from "qrcode.react";
import type {AccountSnapshot} from "@/lib/account-store";
import {FriendError,normalizeFriendCode,type FriendPreview,type FriendRecord,type FriendState,type FriendStore} from "@/lib/friend-store";
import {CharacterPreview3D,LandPreview3D} from "./CustomizationPreview3D";

type ScannerProps={onValue:(value:string)=>void};
function QrScanner({onValue}:ScannerProps){
  const video=useRef<HTMLVideoElement>(null);const stream=useRef<MediaStream|null>(null);const timer=useRef<number|null>(null);const [status,setStatus]=useState<"idle"|"requesting"|"active"|"error"|"unsupported">("idle");const [message,setMessage]=useState("");
  const stop=()=>{if(timer.current!==null)window.clearInterval(timer.current);timer.current=null;stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;setStatus("idle");};
  useEffect(()=>()=>{if(timer.current!==null)window.clearInterval(timer.current);stream.current?.getTracks().forEach(track=>track.stop());},[]);
  const start=async()=>{setStatus("requesting");setMessage("");try{
    const Detector=(window as unknown as {BarcodeDetector?:new(options:{formats:string[]})=>{detect:(source:HTMLVideoElement)=>Promise<Array<{rawValue:string}>>}}).BarcodeDetector;
    if(!Detector){setStatus("unsupported");setMessage("QR scanning is not supported in this browser. Enter the code below instead.");return;}
    const media=await navigator.mediaDevices?.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});if(!media)throw new Error("Camera unavailable");stream.current=media;if(video.current){video.current.srcObject=media;await video.current.play();}
    setStatus("active");const detector=new Detector({formats:["qr_code"]});timer.current=window.setInterval(async()=>{if(!video.current)return;try{const results=await detector.detect(video.current);const raw=results[0]?.rawValue;if(raw){let value=raw;try{const url=new URL(raw);value=url.searchParams.get("invite")??url.searchParams.get("code")??raw;}catch{}onValue(value);stop();}}catch{}},500);
  }catch(error){setStatus("error");setMessage(error instanceof DOMException&&error.name==="NotAllowedError"?"Camera access was denied. Allow it in browser settings or enter the code manually.":"The camera could not start. Enter the code manually instead.");}};
  return <div className="qr-scanner">{status==="active"?<><video ref={video} muted playsInline/><button onClick={stop}>Stop camera</button></>:<button className="scan-button" onClick={start} disabled={status==="requesting"}><Camera/>{status==="requesting"?"Opening camera…":"Scan QR code"}</button>}{message&&<p role="alert">{message}</p>}</div>;
}

export function FriendCenter({actor,state,store,onRefresh,onClose,onPlace,onHide,onRemove,onBlock}:{actor:AccountSnapshot;state:FriendState;store:FriendStore;onRefresh:()=>Promise<void>;onClose:()=>void;onPlace:(friend:FriendRecord)=>void;onHide:(friend:FriendRecord)=>void;onRemove:(friend:FriendRecord)=>void;onBlock:(friend:FriendRecord)=>void}){
  const [tab,setTab]=useState<"mine"|"add"|"requests"|"friends">("mine");const [code,setCode]=useState("");const [preview,setPreview]=useState<FriendPreview|null>(null);const [error,setError]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
  const [openMenu,setOpenMenu]=useState<{userId:string;top:number;right:number}|null>(null);
  const menuFriend=state.friends.find(friend=>friend.preview.userId===openMenu?.userId);
  useEffect(()=>{if(!openMenu)return;const close=(event:PointerEvent)=>{if(!(event.target as Element).closest(".friend-more-trigger,.friend-more-menu"))setOpenMenu(null);};const dismiss=()=>setOpenMenu(null);const escape=(event:KeyboardEvent)=>{if(event.key==="Escape")dismiss();};document.addEventListener("pointerdown",close);document.addEventListener("keydown",escape);window.addEventListener("resize",dismiss);window.addEventListener("scroll",dismiss,true);return()=>{document.removeEventListener("pointerdown",close);document.removeEventListener("keydown",escape);window.removeEventListener("resize",dismiss);window.removeEventListener("scroll",dismiss,true);};},[openMenu]);
  const toggleMenu=(userId:string,button:HTMLButtonElement)=>{if(openMenu?.userId===userId){setOpenMenu(null);return;}const rect=button.getBoundingClientRect();const height=94;setOpenMenu({userId,top:window.innerHeight-rect.bottom<height+10?Math.max(8,rect.top-height-6):rect.bottom+6,right:Math.max(8,window.innerWidth-rect.right)});};
  const act=async(action:()=>Promise<void>,success:string)=>{setBusy(true);setError("");setMessage("");try{await action();setMessage(success);await onRefresh();}catch(reason){setError(reason instanceof FriendError?reason.message:"The friend service is unavailable. Try again.");}finally{setBusy(false);}};
  const lookup=async(value=code)=>{setBusy(true);setError("");setPreview(null);try{const result=await store.preview(value);if(result.userId===actor.userId)throw new FriendError("self_invite","That’s your own friend code.");setPreview(result);setCode(result.code);}catch(reason){setError(reason instanceof FriendError?reason.message:"Couldn’t look up that code.");}finally{setBusy(false);}};
  const copy=async(value:string)=>{await navigator.clipboard.writeText(value);setMessage("Copied.");};
  return <><div className="sheet-backdrop" onPointerDown={onClose}><section className="bottom-sheet friend-center" onPointerDown={event=>event.stopPropagation()}><button className="sheet-close" onClick={onClose}><X/></button><p className="eyebrow">YOUR PLUOTO PEOPLE</p><h2>Friends</h2><nav className="friend-tabs"><button className={tab==="mine"?"active":""} onClick={()=>{setTab("mine");setOpenMenu(null);}}>My invite</button><button className={tab==="add"?"active":""} onClick={()=>{setTab("add");setOpenMenu(null);}}>Add friend</button><button className={tab==="requests"?"active":""} onClick={()=>{setTab("requests");setOpenMenu(null);}}>Requests{state.incoming.length+state.outgoing.length>0&&<b>{state.incoming.length+state.outgoing.length}</b>}</button><button className={tab==="friends"?"active":""} onClick={()=>setTab("friends")}>Friends{state.friends.length>0&&<b>{state.friends.length}</b>}</button></nav>
    {tab==="mine"&&<div className="friend-mine"><div className="qr"><QRCodeSVG value={state.invite.url} size={168} fgColor="#14283c" bgColor="#fffdf7" level="M"/></div><div className="friend-code"><span>{state.invite.code}</span><button onClick={()=>copy(state.invite.code)} aria-label="Copy friend code"><Copy size={16}/></button></div><button className="primary wide" onClick={()=>copy(state.invite.url)}><Link2 size={17}/> Copy invitation link</button><output className="friend-invite-url" aria-label="Invitation link">{state.invite.url}</output>{!state.invite.shareable&&<div className="local-link-warning">Local-only preview link. Set <code>NEXT_PUBLIC_APP_ORIGIN</code> to the deployed HTTPS origin before sharing with another device.</div>}<button className="text-button" disabled={busy} onClick={()=>act(()=>store.regenerateInvite(actor).then(()=>undefined),"Old invitation revoked. A new link and code are ready.")}><RefreshCw size={14}/> Revoke and regenerate</button></div>}
    {tab==="add"&&<div className="friend-add"><QrScanner onValue={value=>{setCode(value);void lookup(value);}}/><div className="or"><i/>or<i/></div><label>Friend code<div><input value={code} placeholder="AB12-CD34" onChange={event=>setCode(normalizeFriendCode(event.target.value))}/><button disabled={busy||code.replace("-","").length!==8} onClick={()=>lookup()}>Preview</button></div></label>{preview&&<FriendPreviewCard preview={preview}><button className="primary wide" disabled={busy} onClick={()=>act(()=>store.sendRequest(actor,preview.code),`Request sent to ${preview.person.nickname}.`)}><UserPlus size={17}/> Send request</button></FriendPreviewCard>}</div>}
    {tab==="requests"&&<div className="friend-list"><h3>Incoming</h3>{state.incoming.length?state.incoming.map(request=><FriendRow key={request.id} preview={request.from}><button className="small-primary" disabled={busy} onClick={()=>act(()=>store.acceptRequest(actor,request.id),`${request.from.person.nickname} is now your friend.`)}>Accept</button><button disabled={busy} onClick={()=>act(()=>store.declineRequest(actor,request.id),"Request declined.")}>Decline</button></FriendRow>):<p className="empty-state">No incoming requests.</p>}<h3>Outgoing</h3>{state.outgoing.length?state.outgoing.map(request=><FriendRow key={request.id} preview={request.to}><span className="pending-chip">Pending</span></FriendRow>):<p className="empty-state">No outgoing requests.</p>}</div>}
    {tab==="friends"&&<div className="friend-list friends-list">{state.friends.length?state.friends.map(friend=><FriendRow key={friend.preview.userId} preview={friend.preview}><button className="small-primary" aria-label={`${friend.placement&&!friend.placement.hidden?"Move":"Place"} ${friend.preview.person.nickname}'s land`} title={friend.placement&&!friend.placement.hidden?"Move land":"Place land"} onClick={()=>onPlace(friend)}><MapPin size={14}/><span className="friend-action-label">{friend.placement&&!friend.placement.hidden?"Move land":"Place land"}</span></button>{friend.placement&&!friend.placement.hidden?<button aria-label={`Hide ${friend.preview.person.nickname}'s land`} title="Hide land" onClick={()=>onHide(friend)}><EyeOff size={14}/><span className="friend-action-label">Hide</span></button>:<span className="friend-action-spacer" aria-hidden="true"/>}<button className="friend-more-trigger" aria-label={`More options for ${friend.preview.person.nickname}`} aria-expanded={openMenu?.userId===friend.preview.userId} title="More options" onClick={event=>toggleMenu(friend.preview.userId,event.currentTarget)}><MoreHorizontal size={18}/></button></FriendRow>):<p className="empty-state">Accepted friends appear here, even before you place their land.</p>}</div>}
    {message&&<div className="friend-feedback success" role="status"><Check size={15}/>{message}</div>}{error&&<div className="friend-feedback error" role="alert">{error}</div>}
  </section></div>{openMenu&&menuFriend&&typeof document!=="undefined"&&createPortal(<div className="friend-more-menu" role="menu" onPointerDown={event=>event.stopPropagation()} style={{position:"fixed",top:openMenu.top,right:openMenu.right}}><button role="menuitem" onClick={()=>{setOpenMenu(null);onRemove(menuFriend);}}><Trash2 size={15}/> Remove friend</button><button className="danger" role="menuitem" onClick={()=>{setOpenMenu(null);onBlock(menuFriend);}}><ShieldOff size={15}/> Block friend</button></div>,document.body)}</>;
}

function FriendRow({preview,children}:{preview:FriendPreview;children:ReactNode}){return <div className="friend-row"><div className="friend-avatar"><CharacterPreview3D person={preview.person}/></div><div><strong>{preview.person.nickname}</strong><span>{preview.person.species} · {preview.person.ground} land</span></div><aside>{children}</aside></div>}
function FriendPreviewCard({preview,children}:{preview:FriendPreview;children:ReactNode}){return <div className="friend-preview"><div><CharacterPreview3D person={preview.person}/><LandPreview3D person={preview.person}/></div><h3>{preview.person.nickname}</h3><p>{preview.person.species} · {preview.person.ground} land · {preview.person.home}</p>{children}</div>}

export function FriendInviteLanding({preview,signedIn,busy,error,onAuthenticate,onAccept,onLater}:{preview:FriendPreview;signedIn:boolean;busy:boolean;error?:string;onAuthenticate:()=>void;onAccept:()=>void;onLater:()=>void}){return <div className="friend-invite-gate"><section><p className="eyebrow">PERSONAL INVITATION</p><h1>{preview.person.nickname} wants to connect.</h1><p>See only their Character and their own land, then choose whether to add each other.</p><div className="invite-world-preview"><LandPreview3D person={preview.person}/></div>{signedIn?<><button className="primary wide" disabled={busy} onClick={onAccept}>Accept invitation</button><button className="text-button" onClick={onLater}>Later</button></>:<><button className="primary wide" onClick={onAuthenticate}>Sign in or create an account</button><p className="quiet-copy">The invitation stays with you through verification and onboarding.</p></>}{error&&<div className="form-error">{error}</div>}</section></div>}
