import {type RealtimeChannel,type SupabaseClient} from "@supabase/supabase-js";
import type {AccountSnapshot} from "./account-store";
import {getSupabaseBrowserClient,hasSupabaseConfig} from "./supabase-client";
import type {Person} from "./types";

export type FriendErrorCode="invalid_code"|"self_invite"|"already_friends"|"pending"|"expired"|"revoked"|"blocked"|"occupied"|"network"|"not_found";
export class FriendError extends Error {constructor(public code:FriendErrorCode,message:string){super(message);}}
export type FriendPreview={userId:string;code:string;person:Person;expiresAt?:number};
export type FriendRequest={id:string;from:FriendPreview;to:FriendPreview;status:"pending"|"accepted"|"declined";createdAt:number};
export type FriendPlacement={plotX:number;plotY:number;hidden:boolean};
export type FriendRecord={preview:FriendPreview;placement?:FriendPlacement};
export type FriendState={invite:{code:string;token:string;url:string;shareable:boolean};incoming:FriendRequest[];outgoing:FriendRequest[];friends:FriendRecord[]};
export type FriendStore={mode:"supabase"|"local";list:(actor:AccountSnapshot)=>Promise<FriendState>;preview:(value:string)=>Promise<FriendPreview>;sendRequest:(actor:AccountSnapshot,code:string)=>Promise<void>;acceptRequest:(actor:AccountSnapshot,id:string)=>Promise<void>;declineRequest:(actor:AccountSnapshot,id:string)=>Promise<void>;acceptInvitation:(actor:AccountSnapshot,token:string)=>Promise<void>;regenerateInvite:(actor:AccountSnapshot)=>Promise<FriendState>;setPlacement:(actor:AccountSnapshot,friendId:string,placement:FriendPlacement|null)=>Promise<void>;removeFriend:(actor:AccountSnapshot,friendId:string)=>Promise<void>;blockUser:(actor:AccountSnapshot,userId:string)=>Promise<void>;subscribe:(actor:AccountSnapshot,onChange:()=>void)=>()=>void};

type InviteRow={userId:string;code:string;token:string;expiresAt:number;revoked:boolean};
type RequestRow={id:string;fromId:string;toId:string;status:"pending"|"accepted"|"declined";createdAt:number};
type RevokedInvite=InviteRow&{reason:"expired"|"revoked"};
type LocalSocial={invites:Record<string,InviteRow>;revokedInvites:RevokedInvite[];requests:RequestRow[];friendships:string[];placements:Record<string,FriendPlacement>;blocks:string[]};
type StorageLike=Pick<Storage,"getItem"|"setItem">;
const SOCIAL_KEY="pluoto-social-v1";
const ACCOUNTS_KEY="pluoto-accounts-v1";
const alphabet="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
const clean=(value:string)=>value.trim().toUpperCase().replace(/[^A-Z0-9]/g,"");
export const normalizeFriendCode=(value:string)=>{const raw=clean(value);return raw.length===8?`${raw.slice(0,4)}-${raw.slice(4)}`:raw;};
const pair=(a:string,b:string)=>[a,b].sort().join(":");
const placementKey=(owner:string,friend:string)=>`${owner}:${friend}`;
function read<T>(storage:StorageLike,key:string,fallback:T):T{try{const value=storage.getItem(key);return value?JSON.parse(value) as T:fallback;}catch{return fallback;}}
function secureCode(existing:Set<string>){for(let attempt=0;attempt<64;attempt++){const bytes=crypto.getRandomValues(new Uint8Array(8));const raw=Array.from(bytes,value=>alphabet[value%alphabet.length]).join("");const code=normalizeFriendCode(raw);if(!existing.has(code))return code;}throw new FriendError("network","Couldn’t create a unique friend code. Try again.");}
function appOrigin(){const configured=process.env.NEXT_PUBLIC_APP_ORIGIN?.replace(/\/$/,"");const current=typeof location!=="undefined"?location.origin:"";if(current&&/^https:\/\//i.test(current)&&!/^https:\/\/(localhost|127\.0\.0\.1)/i.test(current))return{origin:current,shareable:true};if(configured&&!/^https?:\/\/(localhost|127\.0\.0\.1)/i.test(configured))return{origin:configured,shareable:true};return{origin:current||"http://127.0.0.1:3000",shareable:false};}

export class LocalFriendStore implements FriendStore {
  readonly mode="local" as const;private channel:BroadcastChannel|null=null;
  constructor(private storage:StorageLike=localStorage,private now=()=>Date.now()){}
  private db(){const stored=read<Partial<LocalSocial>>(this.storage,SOCIAL_KEY,{});return{invites:stored.invites??{},revokedInvites:stored.revokedInvites??[],requests:stored.requests??[],friendships:stored.friendships??[],placements:stored.placements??{},blocks:stored.blocks??[]};}
  private accounts(){return read<Record<string,AccountSnapshot>>(this.storage,ACCOUNTS_KEY,{});}
  private save(db:LocalSocial){this.storage.setItem(SOCIAL_KEY,JSON.stringify(db));this.channel?.postMessage("change");}
  private profile(id:string):FriendPreview{const account=Object.values(this.accounts()).find(item=>item.userId===id);const invite=this.db().invites[id];if(!account||!invite)throw new FriendError("not_found","That Pluoto person is unavailable.");return{userId:id,code:invite.code,person:account.person,expiresAt:invite.expiresAt};}
  private ensure(actor:AccountSnapshot,db:LocalSocial){let invite=db.invites[actor.userId];if(invite&&(invite.revoked||invite.expiresAt<this.now()))db.revokedInvites.push({...invite,reason:invite.revoked?"revoked":"expired"});if(!invite||invite.revoked||invite.expiresAt<this.now()){const codes=new Set([...Object.values(db.invites).map(item=>item.code),...db.revokedInvites.map(item=>item.code)]);invite={userId:actor.userId,code:secureCode(codes),token:crypto.randomUUID(),expiresAt:this.now()+90*86_400_000,revoked:false};db.invites[actor.userId]=invite;}return invite;}
  async list(actor:AccountSnapshot){const db=this.db();const invite=this.ensure(actor,db);this.save(db);const {origin,shareable}=appOrigin();const incoming=db.requests.filter(item=>item.toId===actor.userId&&item.status==="pending").map(item=>this.request(item));const outgoing=db.requests.filter(item=>item.fromId===actor.userId&&item.status==="pending").map(item=>this.request(item));const ids=db.friendships.filter(item=>item.split(":").includes(actor.userId)).map(item=>item.split(":").find(id=>id!==actor.userId)!).filter(Boolean);return{invite:{code:invite.code,token:invite.token,url:`${origin}/?invite=${encodeURIComponent(invite.token)}`,shareable},incoming,outgoing,friends:ids.map(id=>({preview:this.profile(id),placement:db.placements[placementKey(actor.userId,id)]}))};}
  private request(row:RequestRow):FriendRequest{return{id:row.id,from:this.profile(row.fromId),to:this.profile(row.toId),status:row.status,createdAt:row.createdAt};}
  async preview(value:string){const db=this.db();const normalized=normalizeFriendCode(value);const invite=Object.values(db.invites).find(item=>item.code===normalized||item.token===value);if(!invite){const old=db.revokedInvites.find(item=>item.code===normalized||item.token===value);if(old)throw new FriendError(old.reason,old.reason==="revoked"?"That invitation was revoked.":"That invitation has expired.");throw new FriendError("invalid_code","That invitation or friend code isn’t valid.");}if(invite.revoked)throw new FriendError("revoked","That invitation was revoked.");if(invite.expiresAt<this.now())throw new FriendError("expired","That invitation has expired.");return this.profile(invite.userId);}
  private assertConnect(db:LocalSocial,actorId:string,targetId:string){if(actorId===targetId)throw new FriendError("self_invite","That’s your own friend code.");if(db.blocks.includes(`${actorId}:${targetId}`)||db.blocks.includes(`${targetId}:${actorId}`))throw new FriendError("blocked","This connection is unavailable.");if(db.friendships.includes(pair(actorId,targetId)))throw new FriendError("already_friends","You’re already friends.");}
  async sendRequest(actor:AccountSnapshot,code:string){const target=await this.preview(code);const db=this.db();this.ensure(actor,db);this.assertConnect(db,actor.userId,target.userId);if(db.requests.some(item=>item.status==="pending"&&pair(item.fromId,item.toId)===pair(actor.userId,target.userId)))throw new FriendError("pending","A request is already pending.");db.requests.push({id:crypto.randomUUID(),fromId:actor.userId,toId:target.userId,status:"pending",createdAt:this.now()});this.save(db);}
  async acceptRequest(actor:AccountSnapshot,id:string){const db=this.db();const request=db.requests.find(item=>item.id===id&&item.toId===actor.userId);if(!request)throw new FriendError("not_found","That request is no longer available.");const key=pair(actor.userId,request.fromId);if(request.status==="accepted"&&db.friendships.includes(key))return;if(request.status!=="pending")throw new FriendError("not_found","That request is no longer available.");this.assertConnect(db,actor.userId,request.fromId);request.status="accepted";if(!db.friendships.includes(key))db.friendships.push(key);this.save(db);}
  async declineRequest(actor:AccountSnapshot,id:string){const db=this.db();const request=db.requests.find(item=>item.id===id&&item.toId===actor.userId&&item.status==="pending");if(!request)throw new FriendError("not_found","That request is no longer available.");request.status="declined";this.save(db);}
  async acceptInvitation(actor:AccountSnapshot,token:string){const target=await this.preview(token);const db=this.db();this.ensure(actor,db);if(actor.userId===target.userId)return;if(db.friendships.includes(pair(actor.userId,target.userId)))return;this.assertConnect(db,actor.userId,target.userId);db.friendships.push(pair(actor.userId,target.userId));const pending=db.requests.find(item=>pair(item.fromId,item.toId)===pair(actor.userId,target.userId)&&item.status==="pending");if(pending)pending.status="accepted";this.save(db);}
  async regenerateInvite(actor:AccountSnapshot){const db=this.db();const current=db.invites[actor.userId];if(current)db.revokedInvites.push({...current,revoked:true,reason:"revoked"});const codes=new Set([...Object.values(db.invites).map(item=>item.code),...db.revokedInvites.map(item=>item.code)]);db.invites[actor.userId]={userId:actor.userId,code:secureCode(codes),token:crypto.randomUUID(),expiresAt:this.now()+90*86_400_000,revoked:false};this.save(db);return this.list(actor);}
  async setPlacement(actor:AccountSnapshot,friendId:string,placement:FriendPlacement|null){const db=this.db();if(!db.friendships.includes(pair(actor.userId,friendId)))throw new FriendError("not_found","That person is not a friend.");const key=placementKey(actor.userId,friendId);const overlapsSaved=placement&&!placement.hidden&&Object.entries(db.placements).some(([candidate,current])=>candidate.startsWith(`${actor.userId}:`)&&candidate!==key&&!current.hidden&&current.plotX===placement.plotX&&current.plotY===placement.plotY);const overlapsArrangement=placement&&!placement.hidden&&actor.arrangement.some(item=>item.personId!==friendId&&item.plotX===placement.plotX&&item.plotY===placement.plotY);if(overlapsSaved||overlapsArrangement)throw new FriendError("occupied","That land block is already occupied.");if(placement)db.placements[key]=placement;else delete db.placements[key];this.save(db);}
  async removeFriend(actor:AccountSnapshot,friendId:string){const db=this.db();db.friendships=db.friendships.filter(item=>item!==pair(actor.userId,friendId));delete db.placements[placementKey(actor.userId,friendId)];delete db.placements[placementKey(friendId,actor.userId)];this.save(db);}
  async blockUser(actor:AccountSnapshot,userId:string){const db=this.db();const block=`${actor.userId}:${userId}`;if(!db.blocks.includes(block))db.blocks.push(block);db.friendships=db.friendships.filter(item=>item!==pair(actor.userId,userId));db.requests=db.requests.filter(item=>pair(item.fromId,item.toId)!==pair(actor.userId,userId));delete db.placements[placementKey(actor.userId,userId)];delete db.placements[placementKey(userId,actor.userId)];this.save(db);}
  subscribe(_actor:AccountSnapshot,onChange:()=>void){this.channel=new BroadcastChannel(SOCIAL_KEY);const message=()=>onChange();const storage=(event:StorageEvent)=>{if(event.key===SOCIAL_KEY||event.key===ACCOUNTS_KEY)onChange();};this.channel.addEventListener("message",message);window.addEventListener("storage",storage);const focus=()=>onChange();window.addEventListener("focus",focus);return()=>{this.channel?.close();this.channel=null;window.removeEventListener("storage",storage);window.removeEventListener("focus",focus);};}
}

class SupabaseFriendStore implements FriendStore {
  readonly mode="supabase" as const;private channels:RealtimeChannel[]=[];
  constructor(private client:SupabaseClient){}
  private async rpc<T>(name:string,args:Record<string,unknown>={}){const result=await this.client.rpc(name,args);if(result.error){const token=(result.error.message.match(/(INVALID_CODE|SELF_INVITE|ALREADY_FRIENDS|PENDING|EXPIRED|REVOKED|BLOCKED|OCCUPIED|NOT_FOUND)/)?.[1]??"").toLowerCase() as FriendErrorCode;throw new FriendError(token||"network",result.error.message.replaceAll("_"," ").toLowerCase());}return result.data as T;}
  async list(_actor:AccountSnapshot){const state=await this.rpc<FriendState>("friend_state");const {origin,shareable}=appOrigin();return{...state,invite:{...state.invite,url:`${origin}/?invite=${encodeURIComponent(state.invite.token)}`,shareable}};}
  async preview(value:string){return this.rpc<FriendPreview>("preview_friend_invite",{p_value:value});}
  async sendRequest(_actor:AccountSnapshot,code:string){await this.rpc("send_friend_request",{p_code:normalizeFriendCode(code)});}
  async acceptRequest(_actor:AccountSnapshot,id:string){await this.rpc("accept_friend_request",{p_request_id:id});}
  async declineRequest(_actor:AccountSnapshot,id:string){await this.rpc("decline_friend_request",{p_request_id:id});}
  async acceptInvitation(_actor:AccountSnapshot,token:string){await this.rpc("accept_personal_invite",{p_token:token});}
  async regenerateInvite(actor:AccountSnapshot){await this.rpc("regenerate_friend_invite");return this.list(actor);}
  async setPlacement(_actor:AccountSnapshot,friendId:string,placement:FriendPlacement|null){await this.rpc("set_friend_placement",{p_friend_id:friendId,p_plot_x:placement?.plotX??null,p_plot_y:placement?.plotY??null,p_hidden:placement?.hidden??false});}
  async removeFriend(_actor:AccountSnapshot,friendId:string){await this.rpc("remove_friend",{p_friend_id:friendId});}
  async blockUser(_actor:AccountSnapshot,userId:string){await this.rpc("block_user",{p_user_id:userId});}
  subscribe(actor:AccountSnapshot,onChange:()=>void){const tables=["friend_requests","friendships","plane_land_placements","lands","user_blocks"];this.channels=tables.map(table=>this.client.channel(`social:${table}:${actor.userId}`).on("postgres_changes",{event:"*",schema:"public",table},onChange).subscribe());const focus=()=>onChange();window.addEventListener("focus",focus);return()=>{this.channels.forEach(channel=>void this.client.removeChannel(channel));this.channels=[];window.removeEventListener("focus",focus);};}
}
export function createFriendStore(storage:StorageLike=localStorage):FriendStore{return hasSupabaseConfig()?new SupabaseFriendStore(getSupabaseBrowserClient()):new LocalFriendStore(storage);}
